export default {
  common: {
    appName: 'Floatr',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    save: 'Save',
    edit: 'Edit',
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Retry',
    search: 'Search',
    send: 'Send',
    next: 'Next',
    back: 'Back',
    done: 'Done',
    skip: 'Skip',
    continue: 'Continue',
    yes: 'Yes',
    no: 'No',
  },
  auth: {
    login: 'Sign In',
    signup: 'Create Account',
    forgotPassword: 'Forgot Password',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    name: 'Full Name',
    loginButton: 'Sign In',
    signupButton: 'Create Account',
    resetPasswordButton: 'Reset Password',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    signupNow: 'Sign up now',
    loginNow: 'Sign in now',
    forgotPasswordLink: 'Forgot your password?',
    resetPasswordSuccess: 'Check your email for reset instructions',
    logoutConfirm: 'Are you sure you want to sign out?',
    deleteAccountConfirm: 'This action cannot be undone. All your data will be permanently deleted.',
  },
  onboarding: {
    welcome: 'Welcome to Floatr',
    welcomeSubtitle: 'Connect with boaters near you',
    step1Title: 'Find Nearby Boaters',
    step1Subtitle: 'Discover boats and crews in your area',
    step2Title: 'Match & Connect',
    step2Subtitle: 'Match with other boaters and start chatting',
    step3Title: 'Meet on the Water',
    step3Subtitle: 'Plan meetups and enjoy your time together',
    getStarted: 'Get Started',
  },
  home: {
    nearby: 'Nearby',
    matches: 'Matches',
    chat: 'Messages',
    profile: 'Profile',
    noNearbyBoaters: 'No boaters nearby',
    noNearbyBoatersSubtitle: 'Try expanding your search radius',
    noMatches: 'No matches yet',
    noMatchesSubtitle: 'Start waving at boaters to get matches',
    noMessages: 'No messages yet',
    noMessagesSubtitle: 'Start chatting with your matches',
  },
  profile: {
    editProfile: 'Edit Profile',
    editBoat: 'Edit Boat Details',
    settings: 'Settings',
    premium: 'Go Premium',
    about: 'About',
    boat: 'Boat',
    photos: 'Photos',
    interests: 'Interests',
    lookingFor: 'Looking For',
    distance: 'Distance',
    lastActive: 'Last Active',
    report: 'Report',
    block: 'Block',
    unmatch: 'Unmatch',
  },
  settings: {
    account: 'Account Settings',
    notifications: 'Notifications',
    privacy: 'Privacy & Safety',
    blockedUsers: 'Blocked Users',
    analytics: 'Analytics & Data',
    help: 'Help & Support',
    terms: 'Terms & Privacy Policy',
    logout: 'Sign Out',
    deleteAccount: 'Delete Account',
    darkMode: 'Dark Mode',
    language: 'Language',
    version: 'Version',
  },
  premium: {
    title: 'Floatr Premium',
    subtitle: 'Unlock all features',
    feature1: 'See who liked you',
    feature2: 'Unlimited likes',
    feature3: 'Advanced filters',
    feature4: 'Profile boosts',
    feature5: 'Ad-free experience',
    monthly: 'Monthly',
    yearly: 'Yearly',
    subscribe: 'Subscribe',
    restore: 'Restore Purchases',
    termsAndPrivacy: 'By subscribing, you agree to our Terms and Privacy Policy',
    savePercent: 'Save %{percent}%',
  },
  help: {
    title: 'How can we help you?',
    subtitle: 'Find answers, get support, and share your feedback',
    faq: 'Frequently Asked Questions',
    faqDescription: 'Find answers to common questions',
    safety: 'Safety Tips',
    safetyDescription: 'Stay safe while using Floatr',
    emergency: 'Emergency Services',
    emergencyDescription: 'Get help in emergency situations',
    feedback: 'Send Feedback',
    feedbackDescription: 'Help us improve Floatr',
    contact: 'Contact Support',
    contactDescription: 'Get in touch with our support team',
    terms: 'Terms of Service',
    termsDescription: 'Read our terms of service',
    privacy: 'Privacy Policy',
    privacyDescription: 'Read our privacy policy',
  },
  feedback: {
    title: 'We Value Your Feedback',
    subtitle: 'Help us improve Floatr by sharing your thoughts and experiences',
    typeQuestion: 'What type of feedback do you have?',
    suggestion: 'Suggestion',
    bug: 'Bug Report',
    other: 'Other',
    ratingQuestion: 'How would you rate your experience?',
    tellUsMore: 'Tell us more',
    feedbackPlaceholder: 'Share your thoughts, ideas, or report issues...',
    submit: 'Submit Feedback',
    thankYou: 'Thank you for your feedback!',
    provideMore: 'Please provide more detailed feedback',
  },
  analytics: {
    title: 'Data Collection Settings',
    subtitle: 'Control how Floatr collects and uses your data to improve the app experience',
    usageAnalytics: 'Usage Analytics',
    usageAnalyticsDescription: 'Collect anonymous data about how you use the app to help us improve features',
    crashReporting: 'Crash Reporting',
    crashReportingDescription: 'Send crash reports to help us identify and fix bugs',
    performanceMonitoring: 'Performance Monitoring',
    performanceMonitoringDescription: 'Track app performance to help us optimize speed and responsiveness',
    userBehaviorTracking: 'User Behavior Tracking',
    userBehaviorTrackingDescription: 'Track detailed user interactions to personalize your experience',
    privacyInfo: 'We take your privacy seriously. All data is collected anonymously and used only to improve the app experience. You can change these settings at any time.',
    dataManagement: 'Data Management',
    deleteData: 'Delete My Analytics Data',
    viewPrivacyPolicy: 'View Privacy Policy',
    deleteConfirm: 'Are you sure you want to delete all your analytics data? This action cannot be undone.',
    dataDeleted: 'Your analytics data has been deleted successfully.',
  },
  notifications: {
    title: 'Push Notifications',
    enable: 'Enable Push Notifications',
    enableDescription: 'Allow Floatr to send you notifications',
    newMatches: 'New Matches',
    newMatchesDescription: 'When someone waves back at you',
    newMessages: 'New Messages',
    newMessagesDescription: 'When you receive a message',
    meetupUpdates: 'Meetup Updates',
    meetupUpdatesDescription: 'Changes to planned meetups',
    nearbyBoaters: 'Nearby Boaters',
    nearbyBoatersDescription: 'When new crews are nearby',
    meetupReminders: 'Meetup Reminders',
    meetupRemindersDescription: 'Remind me before scheduled meetups',
    safetyAlerts: 'Safety Alerts',
    safetyAlertsDescription: 'Weather warnings and safety updates',
    sounds: 'Notification Sounds',
    soundsDescription: 'Play sounds with notifications',
  },
  errors: {
    general: 'Something went wrong. Please try again.',
    network: 'Network error. Please check your connection.',
    auth: 'Authentication error. Please sign in again.',
    server: 'Server error. Please try again later.',
    validation: 'Please check your input and try again.',
    notFound: 'The requested resource was not found.',
    permission: 'You do not have permission to perform this action.',
    timeout: 'Request timed out. Please try again.',
  },
};