export default {
  common: {
    appName: 'Floatr',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    delete: 'Eliminar',
    save: 'Guardar',
    edit: 'Editar',
    loading: 'Cargando...',
    error: 'Algo salió mal',
    retry: 'Reintentar',
    search: 'Buscar',
    send: 'Enviar',
    next: 'Siguiente',
    back: 'Atrás',
    done: 'Listo',
    skip: 'Omitir',
    continue: 'Continuar',
    yes: 'Sí',
    no: 'No',
  },
  auth: {
    login: 'Iniciar Sesión',
    signup: 'Crear Cuenta',
    forgotPassword: 'Olvidé mi Contraseña',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    name: 'Nombre Completo',
    loginButton: 'Iniciar Sesión',
    signupButton: 'Crear Cuenta',
    resetPasswordButton: 'Restablecer Contraseña',
    noAccount: "¿No tienes una cuenta?",
    haveAccount: '¿Ya tienes una cuenta?',
    signupNow: 'Regístrate ahora',
    loginNow: 'Inicia sesión ahora',
    forgotPasswordLink: '¿Olvidaste tu contraseña?',
    resetPasswordSuccess: 'Revisa tu correo para instrucciones de restablecimiento',
    logoutConfirm: '¿Estás seguro de que quieres cerrar sesión?',
    deleteAccountConfirm: 'Esta acción no se puede deshacer. Todos tus datos serán eliminados permanentemente.',
  },
  onboarding: {
    welcome: 'Bienvenido a Floatr',
    welcomeSubtitle: 'Conéctate con navegantes cerca de ti',
    step1Title: 'Encuentra Navegantes Cercanos',
    step1Subtitle: 'Descubre barcos y tripulaciones en tu área',
    step2Title: 'Conecta y Combina',
    step2Subtitle: 'Haz match con otros navegantes y comienza a chatear',
    step3Title: 'Reúnete en el Agua',
    step3Subtitle: 'Planifica encuentros y disfruta tu tiempo juntos',
    getStarted: 'Comenzar',
  },
  home: {
    nearby: 'Cercanos',
    matches: 'Matches',
    chat: 'Mensajes',
    profile: 'Perfil',
    noNearbyBoaters: 'No hay navegantes cercanos',
    noNearbyBoatersSubtitle: 'Intenta ampliar tu radio de búsqueda',
    noMatches: 'Aún no hay matches',
    noMatchesSubtitle: 'Comienza a saludar a navegantes para conseguir matches',
    noMessages: 'Aún no hay mensajes',
    noMessagesSubtitle: 'Comienza a chatear con tus matches',
  },
  profile: {
    editProfile: 'Editar Perfil',
    editBoat: 'Editar Detalles del Barco',
    settings: 'Configuración',
    premium: 'Hazte Premium',
    about: 'Acerca de',
    boat: 'Barco',
    photos: 'Fotos',
    interests: 'Intereses',
    lookingFor: 'Buscando',
    distance: 'Distancia',
    lastActive: 'Última Actividad',
    report: 'Reportar',
    block: 'Bloquear',
    unmatch: 'Desemparejar',
  },
  settings: {
    account: 'Configuración de Cuenta',
    notifications: 'Notificaciones',
    privacy: 'Privacidad y Seguridad',
    blockedUsers: 'Usuarios Bloqueados',
    analytics: 'Análisis y Datos',
    help: 'Ayuda y Soporte',
    terms: 'Términos y Política de Privacidad',
    logout: 'Cerrar Sesión',
    deleteAccount: 'Eliminar Cuenta',
    darkMode: 'Modo Oscuro',
    language: 'Idioma',
    version: 'Versión',
  },
  premium: {
    title: 'Floatr Premium',
    subtitle: 'Desbloquea todas las funciones',
    feature1: 'Ve quién te ha dado like',
    feature2: 'Likes ilimitados',
    feature3: 'Filtros avanzados',
    feature4: 'Impulsos de perfil',
    feature5: 'Experiencia sin anuncios',
    monthly: 'Mensual',
    yearly: 'Anual',
    subscribe: 'Suscribirse',
    restore: 'Restaurar Compras',
    termsAndPrivacy: 'Al suscribirte, aceptas nuestros Términos y Política de Privacidad',
    savePercent: 'Ahorra %{percent}%',
  },
  help: {
    title: '¿Cómo podemos ayudarte?',
    subtitle: 'Encuentra respuestas, obtén soporte y comparte tus comentarios',
    faq: 'Preguntas Frecuentes',
    faqDescription: 'Encuentra respuestas a preguntas comunes',
    safety: 'Consejos de Seguridad',
    safetyDescription: 'Mantente seguro mientras usas Floatr',
    emergency: 'Servicios de Emergencia',
    emergencyDescription: 'Obtén ayuda en situaciones de emergencia',
    feedback: 'Enviar Comentarios',
    feedbackDescription: 'Ayúdanos a mejorar Floatr',
    contact: 'Contactar Soporte',
    contactDescription: 'Ponte en contacto con nuestro equipo de soporte',
    terms: 'Términos de Servicio',
    termsDescription: 'Lee nuestros términos de servicio',
    privacy: 'Política de Privacidad',
    privacyDescription: 'Lee nuestra política de privacidad',
  },
  feedback: {
    title: 'Valoramos tus Comentarios',
    subtitle: 'Ayúdanos a mejorar Floatr compartiendo tus pensamientos y experiencias',
    typeQuestion: '¿Qué tipo de comentario tienes?',
    suggestion: 'Sugerencia',
    bug: 'Reporte de Error',
    other: 'Otro',
    ratingQuestion: '¿Cómo calificarías tu experiencia?',
    tellUsMore: 'Cuéntanos más',
    feedbackPlaceholder: 'Comparte tus pensamientos, ideas o reporta problemas...',
    submit: 'Enviar Comentario',
    thankYou: '¡Gracias por tus comentarios!',
    provideMore: 'Por favor proporciona comentarios más detallados',
  },
  analytics: {
    title: 'Configuración de Recopilación de Datos',
    subtitle: 'Controla cómo Floatr recopila y utiliza tus datos para mejorar la experiencia de la app',
    usageAnalytics: 'Análisis de Uso',
    usageAnalyticsDescription: 'Recopilar datos anónimos sobre cómo usas la app para ayudarnos a mejorar las funciones',
    crashReporting: 'Informes de Fallos',
    crashReportingDescription: 'Enviar informes de fallos para ayudarnos a identificar y corregir errores',
    performanceMonitoring: 'Monitoreo de Rendimiento',
    performanceMonitoringDescription: 'Seguimiento del rendimiento de la app para ayudarnos a optimizar la velocidad y capacidad de respuesta',
    userBehaviorTracking: 'Seguimiento de Comportamiento',
    userBehaviorTrackingDescription: 'Seguimiento detallado de interacciones para personalizar tu experiencia',
    privacyInfo: 'Nos tomamos tu privacidad en serio. Todos los datos se recopilan de forma anónima y se utilizan solo para mejorar la experiencia de la app. Puedes cambiar esta configuración en cualquier momento.',
    dataManagement: 'Gestión de Datos',
    deleteData: 'Eliminar Mis Datos de Análisis',
    viewPrivacyPolicy: 'Ver Política de Privacidad',
    deleteConfirm: '¿Estás seguro de que deseas eliminar todos tus datos de análisis? Esta acción no se puede deshacer.',
    dataDeleted: 'Tus datos de análisis se han eliminado correctamente.',
  },
  notifications: {
    title: 'Notificaciones Push',
    enable: 'Habilitar Notificaciones Push',
    enableDescription: 'Permitir que Floatr te envíe notificaciones',
    newMatches: 'Nuevos Matches',
    newMatchesDescription: 'Cuando alguien te devuelve el saludo',
    newMessages: 'Nuevos Mensajes',
    newMessagesDescription: 'Cuando recibes un mensaje',
    meetupUpdates: 'Actualizaciones de Encuentros',
    meetupUpdatesDescription: 'Cambios en encuentros planificados',
    nearbyBoaters: 'Navegantes Cercanos',
    nearbyBoatersDescription: 'Cuando hay nuevas tripulaciones cerca',
    meetupReminders: 'Recordatorios de Encuentros',
    meetupRemindersDescription: 'Recuérdame antes de los encuentros programados',
    safetyAlerts: 'Alertas de Seguridad',
    safetyAlertsDescription: 'Advertencias meteorológicas y actualizaciones de seguridad',
    sounds: 'Sonidos de Notificación',
    soundsDescription: 'Reproducir sonidos con las notificaciones',
  },
  errors: {
    general: 'Algo salió mal. Por favor, inténtalo de nuevo.',
    network: 'Error de red. Por favor, verifica tu conexión.',
    auth: 'Error de autenticación. Por favor, inicia sesión de nuevo.',
    server: 'Error del servidor. Por favor, inténtalo más tarde.',
    validation: 'Por favor, verifica tu entrada e inténtalo de nuevo.',
    notFound: 'El recurso solicitado no fue encontrado.',
    permission: 'No tienes permiso para realizar esta acción.',
    timeout: 'La solicitud expiró. Por favor, inténtalo de nuevo.',
  },
};