export default {
  common: {
    appName: 'Floatr',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    delete: 'Supprimer',
    save: 'Enregistrer',
    edit: 'Modifier',
    loading: 'Chargement...',
    error: 'Une erreur est survenue',
    retry: 'Réessayer',
    search: 'Rechercher',
    send: 'Envoyer',
    next: 'Suivant',
    back: 'Retour',
    done: 'Terminé',
    skip: 'Passer',
    continue: 'Continuer',
    yes: 'Oui',
    no: 'Non',
  },
  auth: {
    login: 'Connexion',
    signup: 'Créer un Compte',
    forgotPassword: 'Mot de Passe Oublié',
    email: 'Email',
    password: 'Mot de Passe',
    confirmPassword: 'Confirmer le Mot de Passe',
    name: 'Nom Complet',
    loginButton: 'Se Connecter',
    signupButton: 'Créer un Compte',
    resetPasswordButton: 'Réinitialiser le Mot de Passe',
    noAccount: "Vous n'avez pas de compte?",
    haveAccount: 'Vous avez déjà un compte?',
    signupNow: 'Inscrivez-vous maintenant',
    loginNow: 'Connectez-vous maintenant',
    forgotPasswordLink: 'Mot de passe oublié?',
    resetPasswordSuccess: 'Vérifiez votre email pour les instructions de réinitialisation',
    logoutConfirm: 'Êtes-vous sûr de vouloir vous déconnecter?',
    deleteAccountConfirm: 'Cette action ne peut pas être annulée. Toutes vos données seront définitivement supprimées.',
  },
  onboarding: {
    welcome: 'Bienvenue sur Floatr',
    welcomeSubtitle: 'Connectez-vous avec des plaisanciers près de chez vous',
    step1Title: 'Trouvez des Plaisanciers à Proximité',
    step1Subtitle: 'Découvrez des bateaux et des équipages dans votre région',
    step2Title: 'Faites des Rencontres',
    step2Subtitle: 'Matchez avec d\'autres plaisanciers et commencez à discuter',
    step3Title: 'Rencontrez-vous sur l\'Eau',
    step3Subtitle: 'Planifiez des rencontres et profitez de votre temps ensemble',
    getStarted: 'Commencer',
  },
  home: {
    nearby: 'À Proximité',
    matches: 'Matchs',
    chat: 'Messages',
    profile: 'Profil',
    noNearbyBoaters: 'Aucun plaisancier à proximité',
    noNearbyBoatersSubtitle: 'Essayez d\'élargir votre rayon de recherche',
    noMatches: 'Pas encore de matchs',
    noMatchesSubtitle: 'Commencez à saluer les plaisanciers pour obtenir des matchs',
    noMessages: 'Pas encore de messages',
    noMessagesSubtitle: 'Commencez à discuter avec vos matchs',
  },
  profile: {
    editProfile: 'Modifier le Profil',
    editBoat: 'Modifier les Détails du Bateau',
    settings: 'Paramètres',
    premium: 'Passer à Premium',
    about: 'À Propos',
    boat: 'Bateau',
    photos: 'Photos',
    interests: 'Intérêts',
    lookingFor: 'Recherche',
    distance: 'Distance',
    lastActive: 'Dernière Activité',
    report: 'Signaler',
    block: 'Bloquer',
    unmatch: 'Supprimer le Match',
  },
  settings: {
    account: 'Paramètres du Compte',
    notifications: 'Notifications',
    privacy: 'Confidentialité et Sécurité',
    blockedUsers: 'Utilisateurs Bloqués',
    analytics: 'Analyses et Données',
    help: 'Aide et Support',
    terms: 'Conditions et Politique de Confidentialité',
    logout: 'Déconnexion',
    deleteAccount: 'Supprimer le Compte',
    darkMode: 'Mode Sombre',
    language: 'Langue',
    version: 'Version',
  },
  premium: {
    title: 'Floatr Premium',
    subtitle: 'Débloquez toutes les fonctionnalités',
    feature1: 'Voir qui vous a aimé',
    feature2: 'Likes illimités',
    feature3: 'Filtres avancés',
    feature4: 'Boosts de profil',
    feature5: 'Expérience sans publicité',
    monthly: 'Mensuel',
    yearly: 'Annuel',
    subscribe: 'S\'abonner',
    restore: 'Restaurer les Achats',
    termsAndPrivacy: 'En vous abonnant, vous acceptez nos Conditions et notre Politique de Confidentialité',
    savePercent: 'Économisez %{percent}%',
  },
  help: {
    title: 'Comment pouvons-nous vous aider?',
    subtitle: 'Trouvez des réponses, obtenez de l\'aide et partagez vos commentaires',
    faq: 'Questions Fréquentes',
    faqDescription: 'Trouvez des réponses aux questions courantes',
    safety: 'Conseils de Sécurité',
    safetyDescription: 'Restez en sécurité en utilisant Floatr',
    emergency: 'Services d\'Urgence',
    emergencyDescription: 'Obtenez de l\'aide en cas d\'urgence',
    feedback: 'Envoyer des Commentaires',
    feedbackDescription: 'Aidez-nous à améliorer Floatr',
    contact: 'Contacter le Support',
    contactDescription: 'Contactez notre équipe de support',
    terms: 'Conditions d\'Utilisation',
    termsDescription: 'Lisez nos conditions d\'utilisation',
    privacy: 'Politique de Confidentialité',
    privacyDescription: 'Lisez notre politique de confidentialité',
  },
  feedback: {
    title: 'Nous Valorisons Vos Commentaires',
    subtitle: 'Aidez-nous à améliorer Floatr en partageant vos pensées et expériences',
    typeQuestion: 'Quel type de commentaire avez-vous?',
    suggestion: 'Suggestion',
    bug: 'Rapport de Bug',
    other: 'Autre',
    ratingQuestion: 'Comment évalueriez-vous votre expérience?',
    tellUsMore: 'Dites-nous en plus',
    feedbackPlaceholder: 'Partagez vos pensées, idées ou signalez des problèmes...',
    submit: 'Soumettre les Commentaires',
    thankYou: 'Merci pour vos commentaires!',
    provideMore: 'Veuillez fournir des commentaires plus détaillés',
  },
  analytics: {
    title: 'Paramètres de Collecte de Données',
    subtitle: 'Contrôlez comment Floatr collecte et utilise vos données pour améliorer l\'expérience de l\'application',
    usageAnalytics: 'Analyses d\'Utilisation',
    usageAnalyticsDescription: 'Collecter des données anonymes sur votre utilisation de l\'application pour nous aider à améliorer les fonctionnalités',
    crashReporting: 'Rapports de Plantage',
    crashReportingDescription: 'Envoyer des rapports de plantage pour nous aider à identifier et corriger les bugs',
    performanceMonitoring: 'Surveillance des Performances',
    performanceMonitoringDescription: 'Suivre les performances de l\'application pour nous aider à optimiser la vitesse et la réactivité',
    userBehaviorTracking: 'Suivi du Comportement',
    userBehaviorTrackingDescription: 'Suivre les interactions détaillées pour personnaliser votre expérience',
    privacyInfo: 'Nous prenons votre confidentialité au sérieux. Toutes les données sont collectées de manière anonyme et utilisées uniquement pour améliorer l\'expérience de l\'application. Vous pouvez modifier ces paramètres à tout moment.',
    dataManagement: 'Gestion des Données',
    deleteData: 'Supprimer Mes Données d\'Analyse',
    viewPrivacyPolicy: 'Voir la Politique de Confidentialité',
    deleteConfirm: 'Êtes-vous sûr de vouloir supprimer toutes vos données d\'analyse? Cette action ne peut pas être annulée.',
    dataDeleted: 'Vos données d\'analyse ont été supprimées avec succès.',
  },
  notifications: {
    title: 'Notifications Push',
    enable: 'Activer les Notifications Push',
    enableDescription: 'Autoriser Floatr à vous envoyer des notifications',
    newMatches: 'Nouveaux Matchs',
    newMatchesDescription: 'Quand quelqu\'un vous renvoie un salut',
    newMessages: 'Nouveaux Messages',
    newMessagesDescription: 'Quand vous recevez un message',
    meetupUpdates: 'Mises à Jour de Rencontres',
    meetupUpdatesDescription: 'Changements aux rencontres planifiées',
    nearbyBoaters: 'Plaisanciers à Proximité',
    nearbyBoatersDescription: 'Quand de nouveaux équipages sont à proximité',
    meetupReminders: 'Rappels de Rencontres',
    meetupRemindersDescription: 'Me rappeler avant les rencontres programmées',
    safetyAlerts: 'Alertes de Sécurité',
    safetyAlertsDescription: 'Avertissements météo et mises à jour de sécurité',
    sounds: 'Sons de Notification',
    soundsDescription: 'Jouer des sons avec les notifications',
  },
  errors: {
    general: 'Une erreur est survenue. Veuillez réessayer.',
    network: 'Erreur de réseau. Veuillez vérifier votre connexion.',
    auth: 'Erreur d\'authentification. Veuillez vous reconnecter.',
    server: 'Erreur de serveur. Veuillez réessayer plus tard.',
    validation: 'Veuillez vérifier vos entrées et réessayer.',
    notFound: 'La ressource demandée n\'a pas été trouvée.',
    permission: 'Vous n\'avez pas la permission d\'effectuer cette action.',
    timeout: 'La requête a expiré. Veuillez réessayer.',
  },
};